### PR TITLE
Kadanes-Algorithm_C++.cpp

### PR DESCRIPTION
**Pull request by Rinevitable**

### CODE REVIEW

**Comment by Rinevitable** [comment]
It's saying Ineligible Repository.
Your PR was submitted to a repository that is not participating in Hacktoberfest. Maintainers of the repository can add the "hacktoberfest" topic to their repository if they wish to participate.

**Comment by Rinevitable** [comment]
why it isn't merged yet

**Comment by cpgeeksadgitm** [comment]
we have to follow all the instructions and maintainers are not always alvailable. Thanks for your contribution. Happy coding. if you haven't update the contributor list in the bottom of the readme.md then please update.

**Comment by Rinevitable** [comment]
I didn't get any response on the branch #46 .
 Have a look.

**Pull request merged**
