### PR TITLE
Binary insertion sort

### PR DESCRIPTION
**Pull request by jaygala223**
added code for binary insertion sort

### CODE REVIEW

**Comment by cpgeeksadgitm** [comment]
@jaygala223 your majority code has been already merged in another pull request and insertion sort must be placed in right folder https://github.com/cp-geeks-adgitm/Hacktoberfest/tree/master/Algorithms/Sorting in this

**Comment by jaygala223** [comment]
Oh okay. I'll submit an updated PR for this. Thanks

**Comment by cpgeeksadgitm** [comment]
@jaygala223 So should I close this?

**Comment by jaygala223** [comment]
Yes

**Pull request closed without merging**
