### PR TITLE
Interpolation Search

### PR DESCRIPTION
**Pull request by pawan-sen**

### CODE REVIEW

**Comment by Nikunj-Aggarwal** [comment]
Please follow naming conventions properly, the file name should be Interpolation_search_C++.cpp.
Thanks for contributing.

**Comment by pawan-sen** [comment]
ok

**Comment by pawan-sen** [comment]
Is it ok now?

**Comment by Nikunj-Aggarwal** [comment]
Thanks for contributing. Looking forward for having more Pull Requests from you.

**Pull request merged**
