### PR TITLE
Create ArrayOperations(MenuDrivenProgram)

### PR DESCRIPTION
**Pull request by Nandini-singh05**
Hey, I'd like to add a menu driven program to perform various operations on arrays under Data-Structures/Arrays.

### CODE REVIEW

**Comment by cpgeeksadgitm** [comment]
@Nandini-singh05 Thank for the opening pr but you could add the driver code along with menu-driven or without it because it is difficult for us to verify the code

**Comment by Nandini-singh05** [comment]
@cpgeeksadgitm I've added some sample input/output so that it's easier to verify the code.

**Comment by cpgeeksadgitm** [comment]
@Nandini-singh05 Great Nandini, but could you please add file extension. If it is a c++ program, then it must have an extension of .cpp.

**Comment by Nandini-singh05** [comment]
@cpgeeksadgitm I've added the extension.

**Comment by cpgeeksadgitm** [comment]
@Nandini-singh05 Great. Thanks for the contribution

Happy hacking

**Pull request merged**
