### PR TITLE
Translated cpp code of DSA course by William Fiset

### PR DESCRIPTION
**Pull request by abhiy2k**
# Data Structures by William fiset cpp code

This folder contains all the cpp code translated from java of the popular course of Data Structures and algorithm on youtube channel of freecodecamp taught by google engineer william fiset.
you can check the video at : https://www.youtube.com/watch?v=RBSGKlAvoiM 
for original code in java : https://github.com/williamfiset/Algorithms#data-structures

### CODE REVIEW

**Comment by abhiy2k** [comment]
This is a Hacktoberfest PR so can you please add the "HACKTOBERFEST-ACCEPTED LABEL" if you merge my pull request .
Thank You

**Comment by cpgeeksadgitm** [comment]
@abhiy2k  Are these all codes are verified as it is difficult for us to verify all the code at once? and please attach the link of the youtube video

**Comment by cpgeeksadgitm** [comment]
Thanks for the contribution!!

Happy Hacktoberfest

**Comment by abhiy2k** [comment]
Thnxs a ton !
can you suggest me more branches to contribute ?

**Pull request merged**
