### PR TITLE
Rutuparna-Computer_Graphics_Algorithms_C

### PR DESCRIPTION
**Pull request by rutuparna07**
Added two algorithms in /Graphics implemented in C
1.Liang-Barsky
2.Bresenham
It would be really helpful if you attach "hacktoberfest-accepted" label.
Thank you

### CODE REVIEW

**Comment by Nikunj-Aggarwal** [comment]
Please follow the naming conventions and structure.
Thanks for contributing.

**Comment by rutuparna07** [comment]
Hey, Thanks for approving the contribution I`ve updated the files with the naming conventions.

**Comment by Nikunj-Aggarwal** [comment]
Your PR still contains some files that can't be merged. Please look into it.

**Comment by rutuparna07** [comment]
Should I keep the readme as it is ? Which file is causing the problem

**Comment by Nikunj-Aggarwal** [comment]
I think Readme changes are causing conflicts. Please look into it.

**Comment by Nikunj-Aggarwal** [comment]
You can remove the Readme.

**Pull request closed without merging**
