### PR TITLE
Added solution for Maximum Subarray on Leetcode

### PR DESCRIPTION
**Pull request by rithvik2607**

### CODE REVIEW

**Comment by rithvik2607** [comment]
Please let me know if any changes are needed. Thanks

**Comment by Nikunj-Aggarwal** [comment]
Please follow naming conventions filename_python.py is required

**Comment by rithvik2607** [comment]
Thanks for replying, the required changes have been made.

**Comment by Nikunj-Aggarwal** [comment]
Looking forward to have more PRs from you.

**Pull request merged**
