### PR TITLE
Solution of Majority Element in java

### PR DESCRIPTION
**Pull request by Shubham20015**
It uses Boyer-Moore Voting Algorithm in this question which is important for many other similar questions.

### CODE REVIEW

**Comment by Nikunj-Aggarwal** [comment]
Please follow the naming conventions properly.
Thanks for contributing.

**Comment by Shubham20015** [comment]
According to me, I give name of file according to your naming conventions.
Please let me know if need any change in File Name or code.

**Comment by Nikunj-Aggarwal** [comment]
The name should be Majority-element_Java.java
and same goes to the other code

**Comment by Nikunj-Aggarwal** [comment]
Thanks for contributing. Looking forward to have more PRs from you.

**Pull request merged**
