### PR TITLE
21_Merge_Two_Sorted_Lists

### PR DESCRIPTION
**Pull request by Rinevitable**
merging 2 sorted lists question no. 21 leetcode

### CODE REVIEW

**Comment by Rinevitable** [comment]
21_Merge_Two_Sorted_Lists

**Comment by Rinevitable** [comment]
96_Unique_Binary_Search_Trees_Pure_DP

**Comment by Rinevitable** [comment]
96_Unique_Binary_Search_Trees_Pure_DP

**Comment by cpgeeksadgitm** [comment]
all seems good but please follow the naming convention

**Comment by Rinevitable** [comment]
can you be more specific what is wrong i.e what should i change
i have already mentioned the leetcode no. of the problem then the name of
the problem

**Comment by Rinevitable** [comment]
Hope it's fine now

**Comment by Rinevitable** [comment]
Waiting to Merge

**Comment by cpgeeksadgitm** [comment]
One file name is incorrect...Merge-Two-Sorted-Lists._C++cpp it must be Merge-Two-Sorted-Lists_C++.cpp. please correct it ,then i wil merge as people are not able to run and its difficult for us to manage.

**Comment by Rinevitable** [comment]
Done

**Comment by cpgeeksadgitm** [comment]
done ..Happy coding..  :)

**Pull request merged**
