### PR TITLE
Create Shortest-path-backtracking_C++.cpp

### PR DESCRIPTION
**Pull request by ShadmanAfzal**

### CODE REVIEW

**Comment by Nikunj-Aggarwal** [comment]
Please follow the naming conventions properly, the file name should be Shortest-path-backtracking_C++.cpp
Thanks for contributing

**Comment by Shadmanafzal786** [comment]
> Please follow the naming conventions properly, the file name should be Shortest-path-backtracking_C++.cpp
> Thanks for contributing

oky I'll do that

**Comment by Nikunj-Aggarwal** [comment]
Please follow the naming conventions properly, the file name should be Shortest-path-backtracking_C++.cpp
Thanks for contributing

**Comment by cpgeeksadgitm** [comment]
Thanks for the contribution

**Pull request merged**
